### ISSUE TITLE
How to launch TeamPilgrim windows?

### ISSUE THREAD

**Issue by user0474975** [StanleyGoldman/TeamPilgrim#5]
Hi,
I managed to get TeamPilgrim to compile in Visual Studio 15 Preview. What I can't figure out is how to get the TeamPilgrim windows (like Pending Changes) like in the screenshot. I installed it as an extension (*.vsix) and I can see it in my extensions list. I set the solution like in the readme file. I cannot find any option anywhere to launch it. What am I doing wrong?

**Comment by StanleyGoldman** [comment]
This was originally programmed against Visual Studio 2012/2013 and abandoned. So i'm not sure how well it works against 2015. It used to add a Pending Changes dialog to the menu, that you can open through there.

**Comment by user0474975** [comment]
Note: Visual Studio Enterprise 15 Preview (this is not the same as Visual Studio 2015, although I would use whichever version TeamPilgrim worked in). Was hoping to have it working by the time 15 is released so when I am forced to migrate to it, I would at least have TeamPilgrim.

I was hoping I could get it to work, but the only pending changes is the awful out-of-the-box one. I guess just getting it to compile and install isn't enough :) 

I don't have any experience with this type of project (I'm a web developer) so I'm hoping someone else out there in the community will still want to work on this at some point...

**Comment by user0474975** [comment]
I know it has been a long time but I just wanted to post here that the issue was with Visual Studio 15 Preview - there was a bug that prevented extensions from working, which is why I couldn't find it once it was installed. The full version of Visual Studio 15 (now Visual Studio 2017) does not have this bug and I have been able to get the plug-in to function (with some work of course). Thank you!

**Comment by StanleyGoldman** [comment]
I'm glad you figured it out man, sorry I didn't reply sooner. Buy yea, I really don't maintain this project anymore.

**Comment by user0474975** [comment]
Well, your reply was more than I expected seeing as how I knew the project was abandoned. I'm just so happy you made this in the first place, I stayed on 2010 as my main VS until literally about a month ago and the fact I got TeamPilgrim working in VS 2015 and then VS 2017 has made my programming life so much better. All the best.
